name: CD_test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: "8080"

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag java-app:$(date +%s)

      #username: ${{ secrets.DOCKER_USERNAME }}
      #password: ${{ secrets.DOCKER_PASSWORD }} 
