name: CD_test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: "8080"

    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker Images
      uses: docker/build-push-action@v5.4.0
      with:
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }} 
