name: CI_test

on:
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
 test:
    runs-on: ubuntu-latest
    env:
        PORT: "8080"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with: 
        java-version: '8'
        distribution: 'temurin'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

    - name: Build with Maven
      run: mvn package -B

    - name: Test with Maven
      run:  mvn test
